name: hopper-dev

services:
  db:
    image: postgres:18.3
    container_name: hopper-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: hopper
      POSTGRES_USER: hopper
      POSTGRES_PASSWORD: hopper
    ports:
      - "5433:5432"
    volumes:
      - hopper-db-dev:/var/lib/postgresql

  idp:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    container_name: hopper-idp-dev
    restart: unless-stopped
    environment:
      JSON_CONFIG_PATH: /app/config.json
    volumes:
      - ./oidc/mock-oauth2-config.json:/app/config.json:ro
    ports:
      - "58539:8080"

volumes:
  hopper-db-dev:
