tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

test {
    useJUnitPlatform()
    testLogging.events 'passed', 'failed', 'skipped'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'net.fabricmc:fabric-loader:0.19.3'

    compileOnly 'org.apache.logging.log4j:log4j-api:2.15.0'
}
