/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientReportModDto } from './clientReportModDto';


export interface ClientReportDto { 
    clientId: string;
    username: string | null;
    side?: string | null;
    mods: Array<ClientReportModDto>;
}

