/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SyncSide } from './syncSide';
import { ClientModDto } from './clientModDto';


export interface ClientDto { 
    id: string;
    clientId: string;
    username?: string | null;
    side: SyncSide;
    lastSeenAt: string;
    lastIpAddress?: string | null;
    mods: Array<ClientModDto>;
    createdAt: string;
}
export namespace ClientDto {
}


