/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityTagHeaderValue } from './entityTagHeaderValue';


export interface FileResult { 
    contentType?: string | null;
    fileDownloadName?: string | null;
    lastModified?: string | null;
    entityTag?: EntityTagHeaderValue | null;
    enableRangeProcessing?: boolean;
}

