/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ImportStatus = {
    Queued: 0,
    Running: 1,
    Completed: 2,
    Failed: 3
} as const;
export type ImportStatus = typeof ImportStatus[keyof typeof ImportStatus];

