/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ImportSourceKind = {
    Upload: 0,
    Url: 1
} as const;
export type ImportSourceKind = typeof ImportSourceKind[keyof typeof ImportSourceKind];

