/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManifestModDtoSize } from './manifestModDtoSize';


export interface ManifestModDto { 
    file: string;
    url: string;
    sha256: string;
    size: ManifestModDtoSize;
    modIds?: Array<string> | null;
}

