/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModSource } from './modSource';
import { SyncSide } from './syncSide';
import { ManifestModDtoSize } from './manifestModDtoSize';
import { ModSide } from './modSide';


export interface ModDto { 
    id: string;
    fileName: string;
    sha256: string;
    size: ManifestModDtoSize;
    uploadedBy?: string | null;
    createdAt: string;
    source: ModSource;
    side: ModSide;
    projectId?: string | null;
    versionId?: string | null;
    projectName?: string | null;
    downloadUrl?: string | null;
    iconSha256?: string | null;
    iconUrl?: string | null;
    bytesMissing?: boolean;
    collidesOn?: SyncSide | null;
}
export namespace ModDto {
}


