/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModImportDtoImportedCount } from './modImportDtoImportedCount';


export interface ModImportDto { 
    id: string;
    sourceName: string;
    sourceKind: number;
    format: number;
    status: number;
    importedCount: ModImportDtoImportedCount;
    skippedCount: ModImportDtoImportedCount;
    pendingCount: ModImportDtoImportedCount;
    failedCount: ModImportDtoImportedCount;
    error?: string | null;
    startedAt?: string | null;
    completedAt?: string | null;
    createdBy?: string | null;
    createdAt: string;
}

