/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportSourceKind } from './importSourceKind';
import { DeleteModsResultDtoDeleted } from './deleteModsResultDtoDeleted';
import { PackFormat } from './packFormat';
import { ImportStatus } from './importStatus';


export interface ModImportDto { 
    id: string;
    sourceName: string;
    sourceKind: ImportSourceKind;
    format: PackFormat;
    status: ImportStatus;
    importedCount: DeleteModsResultDtoDeleted;
    skippedCount: DeleteModsResultDtoDeleted;
    pendingCount: DeleteModsResultDtoDeleted;
    failedCount: DeleteModsResultDtoDeleted;
    error?: string | null;
    startedAt?: string | null;
    completedAt?: string | null;
    createdBy?: string | null;
    createdAt: string;
}
export namespace ModImportDto {
}


