/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModLoader = {
    Unknown: 0,
    Forge: 1,
    NeoForge: 2,
    Fabric: 3,
    Quilt: 4
} as const;
export type ModLoader = typeof ModLoader[keyof typeof ModLoader];

