/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModLoader = {
    Unknown: 'Unknown',
    Forge: 'Forge',
    NeoForge: 'NeoForge',
    Fabric: 'Fabric',
    Quilt: 'Quilt'
} as const;
export type ModLoader = typeof ModLoader[keyof typeof ModLoader];

