/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManifestModDtoSize } from './manifestModDtoSize';
import { DeleteModsResultDtoDeleted } from './deleteModsResultDtoDeleted';
import { PlanNodeStatus } from './planNodeStatus';


export interface ModrinthPlanNodeDto { 
    projectId: string;
    slug?: string | null;
    title: string;
    iconUrl?: string | null;
    versionId: string;
    versionNumber?: string | null;
    versionType?: string | null;
    fileName: string;
    fileSize: ManifestModDtoSize;
    status: PlanNodeStatus;
    depth: DeleteModsResultDtoDeleted;
    requiredBy: Array<string>;
    pinned: boolean;
    prerelease: boolean;
}
export namespace ModrinthPlanNodeDto {
}


