/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManifestModDtoSize } from './manifestModDtoSize';


export interface ModrinthProjectDto { 
    id: string;
    slug?: string | null;
    title: string;
    description?: string | null;
    body?: string | null;
    iconUrl?: string | null;
    sourceUrl?: string | null;
    issuesUrl?: string | null;
    downloads: ManifestModDtoSize;
    followers: ManifestModDtoSize;
    categories: Array<string>;
    loaders: Array<string>;
    gameVersions: Array<string>;
}

