/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModImportDtoImportedCount } from './modImportDtoImportedCount';
import { ModrinthSearchHitDto } from './modrinthSearchHitDto';


export interface ModrinthSearchResultDto { 
    hits: Array<ModrinthSearchHitDto>;
    offset: ModImportDtoImportedCount;
    limit: ModImportDtoImportedCount;
    totalHits: ModImportDtoImportedCount;
}

