/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManifestModDtoSize } from './manifestModDtoSize';
import { ModImportDtoImportedCount } from './modImportDtoImportedCount';


export interface ModrinthPlanNodeDto { 
    projectId: string;
    slug?: string | null;
    title: string;
    iconUrl?: string | null;
    versionId: string;
    versionNumber?: string | null;
    versionType?: string | null;
    fileName: string;
    fileSize: ManifestModDtoSize;
    kind: number;
    status: number;
    depth: ModImportDtoImportedCount;
    requiredBy: Array<string>;
    pinned: boolean;
    prerelease: boolean;
}

