/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModrinthSearchIndex = {
    Relevance: 0,
    Downloads: 1,
    Follows: 2,
    Newest: 3,
    Updated: 4
} as const;
export type ModrinthSearchIndex = typeof ModrinthSearchIndex[keyof typeof ModrinthSearchIndex];

