/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManifestModDtoSize } from './manifestModDtoSize';


export interface ModrinthVersionDto { 
    id: string;
    projectId: string;
    name?: string | null;
    versionNumber?: string | null;
    versionType?: string | null;
    datePublished?: string | null;
    fileName?: string | null;
    fileSize?: ManifestModDtoSize;
    installed: boolean;
}

