/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModrinthGameVersionDto } from './modrinthGameVersionDto';


export interface ModrinthTagsDto { 
    loaders: Array<string>;
    gameVersions: Array<ModrinthGameVersionDto>;
}

