/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeleteModsResultDtoDeleted } from './deleteModsResultDtoDeleted';
import { ModrinthSearchHitDto } from './modrinthSearchHitDto';


export interface ModrinthSearchResultDto { 
    hits: Array<ModrinthSearchHitDto>;
    offset: DeleteModsResultDtoDeleted;
    limit: DeleteModsResultDtoDeleted;
    totalHits: DeleteModsResultDtoDeleted;
}

