/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModrinthPlanNodeDto } from './modrinthPlanNodeDto';
import { ModrinthEmbeddedDto } from './modrinthEmbeddedDto';
import { ModrinthUnresolvableDto } from './modrinthUnresolvableDto';
import { ModrinthIncompatibleDto } from './modrinthIncompatibleDto';


export interface ModrinthInstallPlanDto { 
    nodes: Array<ModrinthPlanNodeDto>;
    optional: Array<ModrinthPlanNodeDto>;
    embedded: Array<ModrinthEmbeddedDto>;
    incompatible: Array<ModrinthIncompatibleDto>;
    unresolvable: Array<ModrinthUnresolvableDto>;
    warnings: Array<string>;
    blocked: boolean;
}

