/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModDto } from './modDto';


export interface ModrinthAdoptedDto { 
    mod: ModDto;
    message: string;
}

