/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModrinthSearchIndex = {
    Relevance: 'Relevance',
    Downloads: 'Downloads',
    Follows: 'Follows',
    Newest: 'Newest',
    Updated: 'Updated'
} as const;
export type ModrinthSearchIndex = typeof ModrinthSearchIndex[keyof typeof ModrinthSearchIndex];

