/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModSource = {
    Manual: 0,
    Modrinth: 1,
    CurseForge: 2
} as const;
export type ModSource = typeof ModSource[keyof typeof ModSource];

