/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModSource = {
    Manual: 'Manual',
    Modrinth: 'Modrinth',
    CurseForge: 'CurseForge'
} as const;
export type ModSource = typeof ModSource[keyof typeof ModSource];

