/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ModSide = {
    Both: 0,
    ClientOnly: 1,
    ServerOnly: 2
} as const;
export type ModSide = typeof ModSide[keyof typeof ModSide];

