/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PackFormat = {
    Unknown: 0,
    Modrinth: 1,
    CurseForge: 2,
    PrismInstance: 3,
    JarArchive: 4
} as const;
export type PackFormat = typeof PackFormat[keyof typeof PackFormat];

