/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PendingReason = {
    NoApiKey: 0,
    Blocked: 1,
    DownloadFailed: 2,
    HashMismatch: 3
} as const;
export type PendingReason = typeof PendingReason[keyof typeof PendingReason];

