/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingModDtoProjectId } from './pendingModDtoProjectId';


export interface PendingModDto { 
    id: string;
    importId: string;
    reason: number;
    displayName?: string | null;
    fileName?: string | null;
    projectId?: PendingModDtoProjectId | null;
    fileId?: PendingModDtoProjectId | null;
    expectedSha1?: string | null;
    sourceUrl?: string | null;
    detail?: string | null;
    createdAt: string;
}

