/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PlanNodeStatus = {
    New: 'New',
    AlreadyInstalled: 'AlreadyInstalled',
    OtherVersionInstalled: 'OtherVersionInstalled',
    FileNameTaken: 'FileNameTaken'
} as const;
export type PlanNodeStatus = typeof PlanNodeStatus[keyof typeof PlanNodeStatus];

