/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PlanNodeKind = {
    Root: 'Root',
    Required: 'Required',
    Optional: 'Optional'
} as const;
export type PlanNodeKind = typeof PlanNodeKind[keyof typeof PlanNodeKind];

