/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PlanNodeKind = {
    Root: 0,
    Required: 1,
    Optional: 2
} as const;
export type PlanNodeKind = typeof PlanNodeKind[keyof typeof PlanNodeKind];

