/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingModDtoProjectId } from './pendingModDtoProjectId';


export interface ProblemDetails { 
    type?: string | null;
    title?: string | null;
    status?: PendingModDtoProjectId | null;
    detail?: string | null;
    instance?: string | null;
}

