/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModLoader } from './modLoader';
import { DeleteModsResultDtoDeleted } from './deleteModsResultDtoDeleted';


export interface ServerDto { 
    id: string;
    name: string;
    slug: string;
    modCount: DeleteModsResultDtoDeleted;
    clientCount: DeleteModsResultDtoDeleted;
    createdAt: string;
    minecraftVersion?: string | null;
    loader: ModLoader;
    loaderVersion?: string | null;
}
export namespace ServerDto {
}


