/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModImportDtoImportedCount } from './modImportDtoImportedCount';


export interface ServerDto { 
    id: string;
    name: string;
    slug: string;
    modCount: ModImportDtoImportedCount;
    clientCount: ModImportDtoImportedCount;
    createdAt: string;
    minecraftVersion?: string | null;
    loader: number;
    loaderVersion?: string | null;
}

