/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModImportDtoImportedCount } from './modImportDtoImportedCount';


export interface StringSegment { 
    buffer?: string | null;
    offset?: ModImportDtoImportedCount;
    length?: ModImportDtoImportedCount;
    value?: string | null;
    hasValue?: boolean;
}

