/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeleteModsResultDtoDeleted } from './deleteModsResultDtoDeleted';


export interface StringSegment { 
    buffer?: string | null;
    offset?: DeleteModsResultDtoDeleted;
    length?: DeleteModsResultDtoDeleted;
    value?: string | null;
    hasValue?: boolean;
}

