/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SyncSide = {
    Client: 0,
    Server: 1
} as const;
export type SyncSide = typeof SyncSide[keyof typeof SyncSide];

