/**
 * HOPPER.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModLoader } from './modLoader';


export interface UpdateServerRequest { 
    name: string;
    minecraftVersion?: string | null;
    loader?: ModLoader;
    loaderVersion?: string | null;
}
export namespace UpdateServerRequest {
}


