tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

def forgespiVersion = findProperty('forgespi1165Version') ?: '1.5.0'
def modlauncherVersion = findProperty('modlauncher1165Version') ?: '8.1.3'

dependencies {
    compileOnly "net.minecraftforge:forgespi:${forgespiVersion}"

    compileOnly "cpw.mods:modlauncher:${modlauncherVersion}"
    compileOnly 'org.apache.logging.log4j:log4j-api:2.15.0'
}
