tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

def forgespiVersion = findProperty('forgespiVersion') ?: '6.0.0'
def modlauncherCoordinate = findProperty('modlauncherCoordinate') ?: 'cpw.mods:modlauncher:10.0.1'

dependencies {
    compileOnly "net.minecraftforge:forgespi:${forgespiVersion}"

    compileOnly modlauncherCoordinate
    compileOnly 'org.apache.logging.log4j:log4j-api:2.19.0'
}

jar {
    manifest.attributes('Automatic-Module-Name': 'hopper')
}
