using System.IO.Compression;
using System.Text;
using HOPPER.Domain.Enums;
using HOPPER.Infrastructure.Interfaces;
using Microsoft.Extensions.Configuration;

namespace HOPPER.Infrastructure.Services
{
    public class LocatorJarBuilder(IConfiguration configuration) : ILocatorJarBuilder
    {
        public const string ConfigEntry = "hopper-server.properties";

        public byte[] Build(Guid serverId, string manifestUrl, string token, ModLoader loader, string? minecraftVersion)
        {
            var selected = LocatorTemplates.For(loader, minecraftVersion);
            var template = Path.Combine(ResolveTemplateDirectory(), selected.FileName);

            if (!File.Exists(template))
                throw new LocatorTemplateMissingException(template);

            var buffer = new MemoryStream();

            try
            {
                using var source = ZipFile.OpenRead(template);

                if (source.GetEntry(selected.MarkerEntry) is null)
                    throw new LocatorTemplateMissingException(template, $"is not the HOPPER {loader} locator jar");

                using (var target = new ZipArchive(buffer, ZipArchiveMode.Create, leaveOpen: true))
                {
                    foreach (var entry in source.Entries)
                    {
                        if (string.Equals(entry.FullName, ConfigEntry, StringComparison.Ordinal))
                            continue;

                        var isDirectory = entry.FullName.EndsWith('/');

                        var copy = target.CreateEntry(
                            entry.FullName,
                            isDirectory ? CompressionLevel.NoCompression : CompressionLevel.Optimal);
                        copy.LastWriteTime = entry.LastWriteTime;

                        if (isDirectory)
                            continue;

                        using var from = entry.Open();
                        using var to = copy.Open();
                        from.CopyTo(to);
                    }

                    var config = target.CreateEntry(ConfigEntry, CompressionLevel.Optimal);
                    using var writer = new StreamWriter(config.Open(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false))
                    {
                        NewLine = "\n",
                    };

                    writer.WriteLine("# Generated by HOPPER. Do not edit - download a fresh jar instead.");
                    writer.WriteLine($"serverId={serverId}");
                    writer.WriteLine($"manifestUrl={manifestUrl}");
                    writer.WriteLine($"token={token}");
                }
            }
            catch (InvalidDataException ex)
            {
                throw new LocatorTemplateMissingException(template, "is not a readable zip archive", ex);
            }

            return buffer.ToArray();
        }

        private string ResolveTemplateDirectory()
        {
            var configured = configuration["Hopper:LocatorTemplateDirectory"];

            return string.IsNullOrWhiteSpace(configured)
                ? Path.Combine(AppContext.BaseDirectory, "locator")
                : Path.GetFullPath(configured, AppContext.BaseDirectory);
        }
    }
}
