tasks.withType(JavaCompile).configureEach {
    options.release = 16
}

def forgespiVersion = findProperty('forgespi1182Version') ?: '4.0.9'
def modlauncherVersion = findProperty('modlauncher1182Version') ?: '9.0.7'

dependencies {
    compileOnly "net.minecraftforge:forgespi:${forgespiVersion}"

    compileOnly "cpw.mods:modlauncher:${modlauncherVersion}"

    compileOnly 'org.apache.logging.log4j:log4j-api:2.14.1'
}

jar {
    manifest.attributes('Automatic-Module-Name': 'hopper')
}
