tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging.events 'passed', 'failed', 'skipped'
}

jar {
    manifest.attributes('Implementation-Version': project.version)
}
